theme: jekyll-theme-minimal
title: Mapping Global Foodscapes
description: Welcome to our class website. 
  Here you can find the tutorials for completion.
  You can also go to the <a href="https://docs.google.com/document/d/1ktxUytArJO10L6vUH_Qcttt8Z-vhYGEzgBd-mcRFVpc/edit">Syllabus</a>,
  and <a href="https://drive.google.com/drive/folders/1aGT54tWmaqV9I3zcex7Wni7NAAmqXRe0">Google Drive</a>.
#show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Tutorial 1
    url: tutorial1
  - title: Tutorial 2
    url: tutorial2
  - title: Tutorial 3
    url: tutorial3
  - title: Tutorial 4
    url: tutorial4
  - title: Tutorial 5
    url: tutorial5
  - title: Tutorial 6
    url: tutorial6
  - title: Tutorial 7
    url: tutorial7
  - title: Resources
    url: resources
